add cookies management
chinoxchen-spree-contrib/spree_analytics_trackers pull request #1
Opened 2021-07-07 23:35 UTC by felmsena

2021-07-07 23:39 UTC, sarriagada commented on app/views/spree/shared/trackers/segment/_page_viewed.js.erb
> +      debugger
quedo un debugger

2021-07-07 23:48 UTC, sarriagada commented on app/assets/javascripts/spree/frontend/get_user_cookie.js
> +    var match = document.cookie.match(new RegExp('(^| )' + name + '=([^;]+)'));
[NITPICK] solo una cuestion estetica y no es obligacion el cambio, pero creo que es la nueva forma de interpolar variables en js:
`var match = document.cookie.match(new RegExp('(^| )' + name + '=([^;]+)'));`
es equivalente a:
`var match = document.cookie.match(new RegExp(`(^| )${name}=([^;]+)`));`

2021-07-07 23:51 UTC, sarriagada approved these changes

2021-07-08 04:34 UTC, chinoxchen requested changes

2021-07-08 04:34 UTC, chinoxchen commented on app/views/spree/shared/trackers/segment/_page_viewed.js.erb
>          analytics.identify('<%= user.id %>', {
El user.id también debe ser obtenido por cookie, sino tendrá el mismo comportamiento antiguo del email

2021-07-08 15:05 UTC, felmsena commented on app/assets/javascripts/spree/frontend/get_user_cookie.js
> +    var match = document.cookie.match(new RegExp('(^| )' + name + '=([^;]+)'));
Mira Maxi! @maxilopezramirez

2021-07-08 15:05 UTC, felmsena commented on app/views/spree/shared/trackers/segment/_page_viewed.js.erb
>          analytics.identify('<%= user.id %>', {
Toda la razón, lo arreglaré

2021-07-09 04:50 UTC, rmartinezapp approved these changes

2021-07-09 15:14 UTC, merged